/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ExamsIndexRouteImport } from './routes/exams.index'
import { Route as ResultsExamIdRouteImport } from './routes/results.$examId'
import { Route as ExamsExamIdInstructionsRouteImport } from './routes/exams.$examId.instructions'
import { Route as ExamsExamIdReviewRouteImport } from './routes/exams.$examId.review'
import { Route as ExamsExamIdTakeRouteImport } from './routes/exams.$examId.take'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsExamIdRoute = ResultsExamIdRouteImport.update({
  id: '/results/$examId',
  path: '/results/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdInstructionsRoute = ExamsExamIdInstructionsRouteImport.update({
  id: '/exams/$examId/instructions',
  path: '/exams/$examId/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdReviewRoute = ExamsExamIdReviewRouteImport.update({
  id: '/exams/$examId/review',
  path: '/exams/$examId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdTakeRoute = ExamsExamIdTakeRouteImport.update({
  id: '/exams/$examId/take',
  path: '/exams/$examId/take',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/results/$examId': typeof ResultsExamIdRoute
  '/exams/': typeof ExamsIndexRoute
  '/exams/$examId/instructions': typeof ExamsExamIdInstructionsRoute
  '/exams/$examId/review': typeof ExamsExamIdReviewRoute
  '/exams/$examId/take': typeof ExamsExamIdTakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/results/$examId': typeof ResultsExamIdRoute
  '/exams': typeof ExamsIndexRoute
  '/exams/$examId/instructions': typeof ExamsExamIdInstructionsRoute
  '/exams/$examId/review': typeof ExamsExamIdReviewRoute
  '/exams/$examId/take': typeof ExamsExamIdTakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/results/$examId': typeof ResultsExamIdRoute
  '/exams/': typeof ExamsIndexRoute
  '/exams/$examId/instructions': typeof ExamsExamIdInstructionsRoute
  '/exams/$examId/review': typeof ExamsExamIdReviewRoute
  '/exams/$examId/take': typeof ExamsExamIdTakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/settings'
    | '/results/$examId'
    | '/exams/'
    | '/exams/$examId/instructions'
    | '/exams/$examId/review'
    | '/exams/$examId/take'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/settings'
    | '/results/$examId'
    | '/exams'
    | '/exams/$examId/instructions'
    | '/exams/$examId/review'
    | '/exams/$examId/take'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/settings'
    | '/results/$examId'
    | '/exams/'
    | '/exams/$examId/instructions'
    | '/exams/$examId/review'
    | '/exams/$examId/take'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  ResultsExamIdRoute: typeof ResultsExamIdRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
  ExamsExamIdInstructionsRoute: typeof ExamsExamIdInstructionsRoute
  ExamsExamIdReviewRoute: typeof ExamsExamIdReviewRoute
  ExamsExamIdTakeRoute: typeof ExamsExamIdTakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$examId': {
      id: '/results/$examId'
      path: '/results/$examId'
      fullPath: '/results/$examId'
      preLoaderRoute: typeof ResultsExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId/instructions': {
      id: '/exams/$examId/instructions'
      path: '/exams/$examId/instructions'
      fullPath: '/exams/$examId/instructions'
      preLoaderRoute: typeof ExamsExamIdInstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId/review': {
      id: '/exams/$examId/review'
      path: '/exams/$examId/review'
      fullPath: '/exams/$examId/review'
      preLoaderRoute: typeof ExamsExamIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId/take': {
      id: '/exams/$examId/take'
      path: '/exams/$examId/take'
      fullPath: '/exams/$examId/take'
      preLoaderRoute: typeof ExamsExamIdTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  ResultsExamIdRoute: ResultsExamIdRoute,
  ExamsIndexRoute: ExamsIndexRoute,
  ExamsExamIdInstructionsRoute: ExamsExamIdInstructionsRoute,
  ExamsExamIdReviewRoute: ExamsExamIdReviewRoute,
  ExamsExamIdTakeRoute: ExamsExamIdTakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
