/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminInstitutionsRouteImport } from './routes/admin.institutions'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ExamsIndexRouteImport } from './routes/exams.index'
import { Route as InstructorIndexRouteImport } from './routes/instructor.index'
import { Route as InstructorAnalyticsRouteImport } from './routes/instructor.analytics'
import { Route as InstructorExamBuilderRouteImport } from './routes/instructor.exam-builder'
import { Route as InstructorProfileRouteImport } from './routes/instructor.profile'
import { Route as InstructorReportsRouteImport } from './routes/instructor.reports'
import { Route as InstructorResultsRouteImport } from './routes/instructor.results'
import { Route as InstructorSettingsRouteImport } from './routes/instructor.settings'
import { Route as ResultsExamIdRouteImport } from './routes/results.$examId'
import { Route as ExamsExamIdInstructionsRouteImport } from './routes/exams.$examId.instructions'
import { Route as ExamsExamIdReviewRouteImport } from './routes/exams.$examId.review'
import { Route as ExamsExamIdTakeRouteImport } from './routes/exams.$examId.take'
import { Route as InstructorQuestionsIndexRouteImport } from './routes/instructor.questions.index'
import { Route as InstructorQuestionsQuestionIdRouteImport } from './routes/instructor.questions.$questionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstitutionsRoute = AdminInstitutionsRouteImport.update({
  id: '/admin/institutions',
  path: '/admin/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/admin/monitoring',
  path: '/admin/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/instructor/',
  path: '/instructor/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorAnalyticsRoute = InstructorAnalyticsRouteImport.update({
  id: '/instructor/analytics',
  path: '/instructor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorExamBuilderRoute = InstructorExamBuilderRouteImport.update({
  id: '/instructor/exam-builder',
  path: '/instructor/exam-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorProfileRoute = InstructorProfileRouteImport.update({
  id: '/instructor/profile',
  path: '/instructor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorReportsRoute = InstructorReportsRouteImport.update({
  id: '/instructor/reports',
  path: '/instructor/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorResultsRoute = InstructorResultsRouteImport.update({
  id: '/instructor/results',
  path: '/instructor/results',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorSettingsRoute = InstructorSettingsRouteImport.update({
  id: '/instructor/settings',
  path: '/instructor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsExamIdRoute = ResultsExamIdRouteImport.update({
  id: '/results/$examId',
  path: '/results/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdInstructionsRoute = ExamsExamIdInstructionsRouteImport.update({
  id: '/exams/$examId/instructions',
  path: '/exams/$examId/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdReviewRoute = ExamsExamIdReviewRouteImport.update({
  id: '/exams/$examId/review',
  path: '/exams/$examId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdTakeRoute = ExamsExamIdTakeRouteImport.update({
  id: '/exams/$examId/take',
  path: '/exams/$examId/take',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorQuestionsIndexRoute =
  InstructorQuestionsIndexRouteImport.update({
    id: '/instructor/questions/',
    path: '/instructor/questions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstructorQuestionsQuestionIdRoute =
  InstructorQuestionsQuestionIdRouteImport.update({
    id: '/instructor/questions/$questionId',
    path: '/instructor/questions/$questionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/institutions': typeof AdminInstitutionsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/exam-builder': typeof InstructorExamBuilderRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/reports': typeof InstructorReportsRoute
  '/instructor/results': typeof InstructorResultsRoute
  '/instructor/settings': typeof InstructorSettingsRoute
  '/results/$examId': typeof ResultsExamIdRoute
  '/admin/': typeof AdminIndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/exams/$examId/instructions': typeof ExamsExamIdInstructionsRoute
  '/exams/$examId/review': typeof ExamsExamIdReviewRoute
  '/exams/$examId/take': typeof ExamsExamIdTakeRoute
  '/instructor/questions/$questionId': typeof InstructorQuestionsQuestionIdRoute
  '/instructor/questions/': typeof InstructorQuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/institutions': typeof AdminInstitutionsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/exam-builder': typeof InstructorExamBuilderRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/reports': typeof InstructorReportsRoute
  '/instructor/results': typeof InstructorResultsRoute
  '/instructor/settings': typeof InstructorSettingsRoute
  '/results/$examId': typeof ResultsExamIdRoute
  '/admin': typeof AdminIndexRoute
  '/exams': typeof ExamsIndexRoute
  '/instructor': typeof InstructorIndexRoute
  '/exams/$examId/instructions': typeof ExamsExamIdInstructionsRoute
  '/exams/$examId/review': typeof ExamsExamIdReviewRoute
  '/exams/$examId/take': typeof ExamsExamIdTakeRoute
  '/instructor/questions/$questionId': typeof InstructorQuestionsQuestionIdRoute
  '/instructor/questions': typeof InstructorQuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/institutions': typeof AdminInstitutionsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/exam-builder': typeof InstructorExamBuilderRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/reports': typeof InstructorReportsRoute
  '/instructor/results': typeof InstructorResultsRoute
  '/instructor/settings': typeof InstructorSettingsRoute
  '/results/$examId': typeof ResultsExamIdRoute
  '/admin/': typeof AdminIndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/exams/$examId/instructions': typeof ExamsExamIdInstructionsRoute
  '/exams/$examId/review': typeof ExamsExamIdReviewRoute
  '/exams/$examId/take': typeof ExamsExamIdTakeRoute
  '/instructor/questions/$questionId': typeof InstructorQuestionsQuestionIdRoute
  '/instructor/questions/': typeof InstructorQuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/settings'
    | '/admin/audit-logs'
    | '/admin/institutions'
    | '/admin/monitoring'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/instructor/analytics'
    | '/instructor/exam-builder'
    | '/instructor/profile'
    | '/instructor/reports'
    | '/instructor/results'
    | '/instructor/settings'
    | '/results/$examId'
    | '/admin/'
    | '/exams/'
    | '/instructor/'
    | '/exams/$examId/instructions'
    | '/exams/$examId/review'
    | '/exams/$examId/take'
    | '/instructor/questions/$questionId'
    | '/instructor/questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/settings'
    | '/admin/audit-logs'
    | '/admin/institutions'
    | '/admin/monitoring'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/instructor/analytics'
    | '/instructor/exam-builder'
    | '/instructor/profile'
    | '/instructor/reports'
    | '/instructor/results'
    | '/instructor/settings'
    | '/results/$examId'
    | '/admin'
    | '/exams'
    | '/instructor'
    | '/exams/$examId/instructions'
    | '/exams/$examId/review'
    | '/exams/$examId/take'
    | '/instructor/questions/$questionId'
    | '/instructor/questions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/settings'
    | '/admin/audit-logs'
    | '/admin/institutions'
    | '/admin/monitoring'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/instructor/analytics'
    | '/instructor/exam-builder'
    | '/instructor/profile'
    | '/instructor/reports'
    | '/instructor/results'
    | '/instructor/settings'
    | '/results/$examId'
    | '/admin/'
    | '/exams/'
    | '/instructor/'
    | '/exams/$examId/instructions'
    | '/exams/$examId/review'
    | '/exams/$examId/take'
    | '/instructor/questions/$questionId'
    | '/instructor/questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminInstitutionsRoute: typeof AdminInstitutionsRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  InstructorAnalyticsRoute: typeof InstructorAnalyticsRoute
  InstructorExamBuilderRoute: typeof InstructorExamBuilderRoute
  InstructorProfileRoute: typeof InstructorProfileRoute
  InstructorReportsRoute: typeof InstructorReportsRoute
  InstructorResultsRoute: typeof InstructorResultsRoute
  InstructorSettingsRoute: typeof InstructorSettingsRoute
  ResultsExamIdRoute: typeof ResultsExamIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
  InstructorIndexRoute: typeof InstructorIndexRoute
  ExamsExamIdInstructionsRoute: typeof ExamsExamIdInstructionsRoute
  ExamsExamIdReviewRoute: typeof ExamsExamIdReviewRoute
  ExamsExamIdTakeRoute: typeof ExamsExamIdTakeRoute
  InstructorQuestionsQuestionIdRoute: typeof InstructorQuestionsQuestionIdRoute
  InstructorQuestionsIndexRoute: typeof InstructorQuestionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/institutions': {
      id: '/admin/institutions'
      path: '/admin/institutions'
      fullPath: '/admin/institutions'
      preLoaderRoute: typeof AdminInstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/instructor'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/analytics': {
      id: '/instructor/analytics'
      path: '/instructor/analytics'
      fullPath: '/instructor/analytics'
      preLoaderRoute: typeof InstructorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/exam-builder': {
      id: '/instructor/exam-builder'
      path: '/instructor/exam-builder'
      fullPath: '/instructor/exam-builder'
      preLoaderRoute: typeof InstructorExamBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/profile': {
      id: '/instructor/profile'
      path: '/instructor/profile'
      fullPath: '/instructor/profile'
      preLoaderRoute: typeof InstructorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/reports': {
      id: '/instructor/reports'
      path: '/instructor/reports'
      fullPath: '/instructor/reports'
      preLoaderRoute: typeof InstructorReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/results': {
      id: '/instructor/results'
      path: '/instructor/results'
      fullPath: '/instructor/results'
      preLoaderRoute: typeof InstructorResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/settings': {
      id: '/instructor/settings'
      path: '/instructor/settings'
      fullPath: '/instructor/settings'
      preLoaderRoute: typeof InstructorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$examId': {
      id: '/results/$examId'
      path: '/results/$examId'
      fullPath: '/results/$examId'
      preLoaderRoute: typeof ResultsExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId/instructions': {
      id: '/exams/$examId/instructions'
      path: '/exams/$examId/instructions'
      fullPath: '/exams/$examId/instructions'
      preLoaderRoute: typeof ExamsExamIdInstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId/review': {
      id: '/exams/$examId/review'
      path: '/exams/$examId/review'
      fullPath: '/exams/$examId/review'
      preLoaderRoute: typeof ExamsExamIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId/take': {
      id: '/exams/$examId/take'
      path: '/exams/$examId/take'
      fullPath: '/exams/$examId/take'
      preLoaderRoute: typeof ExamsExamIdTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/questions/': {
      id: '/instructor/questions/'
      path: '/instructor/questions'
      fullPath: '/instructor/questions/'
      preLoaderRoute: typeof InstructorQuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/questions/$questionId': {
      id: '/instructor/questions/$questionId'
      path: '/instructor/questions/$questionId'
      fullPath: '/instructor/questions/$questionId'
      preLoaderRoute: typeof InstructorQuestionsQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminInstitutionsRoute: AdminInstitutionsRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  InstructorAnalyticsRoute: InstructorAnalyticsRoute,
  InstructorExamBuilderRoute: InstructorExamBuilderRoute,
  InstructorProfileRoute: InstructorProfileRoute,
  InstructorReportsRoute: InstructorReportsRoute,
  InstructorResultsRoute: InstructorResultsRoute,
  InstructorSettingsRoute: InstructorSettingsRoute,
  ResultsExamIdRoute: ResultsExamIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ExamsIndexRoute: ExamsIndexRoute,
  InstructorIndexRoute: InstructorIndexRoute,
  ExamsExamIdInstructionsRoute: ExamsExamIdInstructionsRoute,
  ExamsExamIdReviewRoute: ExamsExamIdReviewRoute,
  ExamsExamIdTakeRoute: ExamsExamIdTakeRoute,
  InstructorQuestionsQuestionIdRoute: InstructorQuestionsQuestionIdRoute,
  InstructorQuestionsIndexRoute: InstructorQuestionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
